/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-09-01 13:54:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/kimseula/Desktop/kimseula/_1_Project/BucketClass_PAP/project/bucketclass/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bucketclass/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1482307844000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar", Long.valueOf(1566828078816L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- Basic Page Needs -->\r\n");
      out.write("<title>BucketClass</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/main-color.css\" id=\"colors\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\"\r\n");
      out.write("\thref=\"/img/favicon-32x32.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Header Container -->\r\n");
      out.write("\t\t<header id=\"header-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Left Side Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"left-side\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/\"><img src=\"/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Main Navigation / End -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Left Side Content / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Right Side Content  -->\r\n");
      out.write("\t\t\t\t\t<div class=\"right-side\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header-widget\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"user-menu\" class=\"user-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!------------------------------------------------->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!------------ user menu content ------------------>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!------------------------------------------------->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Right Side Content / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Header / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t<!-- Header Container / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Banner -->\r\n");
      out.write("\t\t<div class=\"main-search-container\"\r\n");
      out.write("\t\t\tdata-background-image=\"/img/main-study.jpg\">\r\n");
      out.write("\t\t\t<div class=\"main-search-inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>가까운 지역의 수업을 찾아보세요!</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-search-input\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"main-search-input-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select data-placeholder=\"카테고리 선택\" class=\"chosen-select\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"sel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\" selected>카테고리 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option id=\"chosen-select-cooking\">요리</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option id=\"chosen-select-art\">예술</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option id=\"chosen-select-language\">외국어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option id=\"chosen-select-health\">헬스케어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option id=\"chosen-select-business\">비즈니스</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option id=\"chosen-select-lifestyle\">일상생활</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"main-search-input-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"input-title\" placeholder=\"키워드를 입력하세요\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"button\" type=\"submit\" onclick=\"searchHandler()\">검색하기</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Content -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"headline centered margin-top-75\">인기 서비스</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Categories Carousel -->\r\n");
      out.write("\t\t<div class=\"fullwidth-carousel-container margin-top-25\">\r\n");
      out.write("\t\t\t<div class=\"fullwidth-slick-carousel category-carousel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"category-box\" data-background-image=\"/img/art.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>예술</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>64 listings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"category-box\" data-background-image=\"/img/language.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>외국어</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>67 listings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"category-box\" data-background-image=\"/img/gym.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>헬스케어</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>27 listings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-half-screen-map-list.html\" class=\"category-box\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-background-image=\"/img/business.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>비즈니스</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>22 listings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-half-screen-map-list.html\" class=\"category-box\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-background-image=\"/img/cooking.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>요리</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>130 listings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"category-box\" data-background-image=\"/img/clean.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>일상생활</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>64 listings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Categories Carousel / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Fullwidth Section -->\r\n");
      out.write("\t\t<section style=\"display: none\"\r\n");
      out.write("\t\t\tclass=\"fullwidth margin-top-65 padding-top-75 padding-bottom-70\"\r\n");
      out.write("\t\t\tdata-background-color=\"#f8f8f8\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"display: none\" class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"headline centered margin-bottom-45\">\r\n");
      out.write("\t\t\t\t\t\t\tMost Visited Places <span>Discover top-rated local\r\n");
      out.write("\t\t\t\t\t\t\t\tbusinesses</span>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"simple-slick-carousel dots-nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"listings-single-page.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"/img/listing-item-01.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-badge now-open\">Now Open</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"tag\">Eat & Drink</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tTom's Restaurant <i class=\"verified-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>964 School Street, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"3.5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(12 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"listings-single-page.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"/img/listing-item-02.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>Friday, August 10</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"tag\">Events</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Sticky Band</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Bishop Avenue, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"5.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(23 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"listings-single-page.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"/img/listing-item-03.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>Starting from $59 per night</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"tag\">Hotels</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Hotel Govendor</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>778 Country Street, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"2.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(17 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"listings-single-page.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"/img/listing-item-04.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-badge now-open\">Now Open</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"tag\">Eat & Drink</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tBurger House <i class=\"verified-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>2726 Shinn Street, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"5.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(31 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"listings-single-page.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"/img/listing-item-05.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"tag\">Other</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Airport</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>1512 Duncan Avenue, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"3.5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(46 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"listings-single-page.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"/img/listing-item-06.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-badge now-closed\">Now Closed</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"tag\">Eat & Drink</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Think Coffee</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>215 Terry Lane, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"4.5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(15 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- Fullwidth Section / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Info Section -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"headline centered margin-top-80\">\r\n");
      out.write("\t\t\t\t\t\t故 신영복 선생 「스승과 제자」 <span class=\"margin-top-25\">\"우리는 저마다 누군가의\r\n");
      out.write("\t\t\t\t\t\t\t제자이면서 동시에 누군가의 스승입니다. 배우고 가르치는 사제(師弟)의 연쇄(連鎖)를 확인하는 것이 곧 자기(自己)의\r\n");
      out.write("\t\t\t\t\t\t\t발견입니다.\"</span>\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row icons-container\">\r\n");
      out.write("\t\t\t\t<!-- Stage -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon-box-2 with-line\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"im im-icon-Mouse-2\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3>원하는 수업을 찾아보세요!</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>Bucket Class에서 제공하는 서비스를 이용하여</span><br> <span>본인이\r\n");
      out.write("\t\t\t\t\t\t\t원하는 수업을 찾아봅시당!</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Stage -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon-box-2 with-line\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"im im-icon-Mail-withAtSign\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3>이메일로 연락을 보내세요!</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>원하는 수업을 찾았다면</span><br> <span>제공자에게 메일을 보내봅시당!</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Stage -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon-box-2 with-line\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"im im-icon-Checked-User\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3>수업 등록완료!</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>제공자와 수업일정을 조율하고</span> <span></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Stage -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"icon-box-2\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"im im-icon-Open-Book\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3>수업시작!</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>드디어 수업이 시작했습니당!</span><br> <span>본인이 원한 수업인 만큼\r\n");
      out.write("\t\t\t\t\t\t\t최선을 다해</span><br> <span>목표를 달성해 보세요!</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Info Section / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Recent Blog Posts -->\r\n");
      out.write("\t\t<section style=\"display: none\"\r\n");
      out.write("\t\t\tclass=\"fullwidth border-top margin-top-70 padding-top-75 padding-bottom-75\"\r\n");
      out.write("\t\t\tdata-background-color=\"#fff\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"headline centered margin-bottom-45\">From The Blog\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<!-- Blog Post Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"pages-blog-post.html\" class=\"blog-compact-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"blog-compact-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/img/blog-compact-post-01.jpg\" alt=\"\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"blog-item-tag\">Tips</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"blog-compact-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"blog-post-tags\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>22 August 2019</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Hotels for All Budgets</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Sed sed tristique nibh iam porta volutpat finibus. Donec\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tin aliquet urneget mattis lorem. Pellentesque pellentesque.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Blog post Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Blog Post Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"pages-blog-post.html\" class=\"blog-compact-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"blog-compact-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/img/blog-compact-post-02.jpg\" alt=\"\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"blog-item-tag\">Tips</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"blog-compact-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"blog-post-tags\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>18 August 2019</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>The 50 Greatest Street Arts In London</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Sed sed tristique nibh iam porta volutpat finibus. Donec\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tin aliquet urneget mattis lorem. Pellentesque pellentesque.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Blog post Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Blog Post Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"pages-blog-post.html\" class=\"blog-compact-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"blog-compact-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/img/blog-compact-post-03.jpg\" alt=\"\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"blog-item-tag\">Tips</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"blog-compact-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"blog-post-tags\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>10 August 2019</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>The Best Cofee Shops In Sydney Neighborhoods</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Sed sed tristique nibh iam porta volutpat finibus. Donec\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tin aliquet urneget mattis lorem. Pellentesque pellentesque.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Blog post Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 centered-content\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"pages-blog.html\" class=\"button border margin-top-10\">View\r\n");
      out.write("\t\t\t\t\t\t\tBlog</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- Recent Blog Posts / End -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t\t\t<div id=\"footer\" class=\"sticky-footer\">\r\n");
      out.write("\t\t\t\t<!-- Main -->\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-5 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"footer-logo\" src=\"img/logo.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>(주)버킷클래스 (대표이사: 송인진)</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>사업자등록번호: 111-22-33333</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>개인정보책임관리자: THE-PAP</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>서울특별시 서초구 서초4동 강남대로 459 B1 5강의실</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>고객센터: 1234-4321</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4 col-sm-6 \">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Helpful Links</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/login\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/signup\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">My Account</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Add Listing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Pricing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Our Partners</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">How It Works</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3  col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Contact Us</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>서울 마포구 마포대로 89 포스트타워 14층</span> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t전화번호: <span>(02) 123-456 </span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t이메일:<span> <a href=\"#\">THE-PAP@pap.com</a> </span><br>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Copyright -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"copyrights\">© 2019 Bucket Class. All Rights Reserved.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Footer / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Back To Top Button -->\r\n");
      out.write("\t\t<div id=\"backtotop\">\r\n");
      out.write("\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Wrapper / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery-2.2.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/mmenu.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/chosen.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/slick.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/rangeslider.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/waypoints.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/counterup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/tooltips.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/apis.js\"></script>\r\n");
      out.write("\t<script src=\"/js/redirect.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/mainSearch.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tlet getRoleName = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rolename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tlet getNickName = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\tif (getRoleName === \"ROLE_CUSTOMER\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar headerContentCustomer = '<div class=\"user-name\"><span><img src=\"\" alt=\"\"></span>[이용자]'\r\n");
      out.write("\t\t\t\t\t+ getNickName\r\n");
      out.write("\t\t\t\t\t+ '님, 안녕하세요!</div>'\r\n");
      out.write("\t\t\t\t\t+ '<ul><li><a href=\"/customer/mypage\"><i class=\"sl sl-icon-settings\"></i> 마이페이지</a></li>'\r\n");
      out.write("\t\t\t\t\t+ '<li><a onclick=\"viewBookmark();\"><i class=\"fa fa-calendar-check-o\"></i> 나의 수강 관리</a></li>'\r\n");
      out.write("\t\t\t\t\t+ '<li><a href=\"/logout\"><i class=\"sl sl-icon-power\"></i> 로그아웃</a></li></ul>';\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.querySelector('#user-menu').innerHTML = headerContentCustomer;\r\n");
      out.write("\r\n");
      out.write("\t\t} else if (getRoleName === \"ROLE_PROVIDER\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar headerContentProvider = '<div class=\"user-name\"><span><img src=\"\" alt=\"\"></span>[제공자]'\r\n");
      out.write("\t\t\t\t\t+ getNickName\r\n");
      out.write("\t\t\t\t\t+ '님, 안녕하세요!</div>'\r\n");
      out.write("\t\t\t\t\t+ '<ul><li><a href=\"/provider/mypage\"><i class=\"sl sl-icon-settings\"></i> 마이페이지</a></li>'\r\n");
      out.write("\t\t\t\t\t+ '<li><a onclick=\"viewMyListing();\"><i class=\"fa fa-calendar-check-o\"></i> 나의 수업 관리</a></li>'\r\n");
      out.write("\t\t\t\t\t+ '<li><a href=\"/logout\"><i class=\"sl sl-icon-power\"></i> 로그아웃</a></li></ul>';\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.querySelector('#user-menu').innerHTML = headerContentProvider;\r\n");
      out.write("\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar headerContent = '<a href=\"/login\" class=\"sign-in\">로그인</a>'\r\n");
      out.write("\t\t\t\t\t+ '<a href=\"/signup\" class=\"sign-in\">회원가입</a>';\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.querySelector('#user-menu').innerHTML = headerContent;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?libraries=places&callback=initAutocomplete\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Style Switcher -->\r\n");
      out.write("\t<script src=\"/js/switcher.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"style-switcher\">\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\tColor Switcher <a href=\"#\"><i class=\"sl sl-icon-settings\"></i></a>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<ul class=\"colors\" id=\"color1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"main\" title=\"Main\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"blue\" title=\"Blue\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"green\" title=\"Green\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"orange\" title=\"Orange\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"navy\" title=\"Navy\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"yellow\" title=\"Yellow\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"peach\" title=\"Peach\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"beige\" title=\"Beige\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"purple\" title=\"Purple\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"celadon\" title=\"Celadon\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"red\" title=\"Red\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"brown\" title=\"Brown\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"cherry\" title=\"Cherry\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"cyan\" title=\"Cyan\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"gray\" title=\"Gray\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"olive\" title=\"Olive\"></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Style Switcher / End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
